### PR TITLE
Fix build for Swift 2.1.1

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by radare** [comment]
Ping

**Comment by svdo** [comment]
Unit tests are failing. I created branch pr/3 for this pull request, please fix there. I also setup Travis CI. Please make sure everything works and resubmit pull request, on branch pr/3. Thanks!

**Comment by trufae** [comment]
I've posted about how to port code from 1 to 2: https://medium.com/@trufae/swifting-from-1-to-2-6d3deeddb15b#.j15lmnop6

i guess that travis issue is because i have to rebase to master to get latest .travis file

**Comment by svdo** [comment]
Thanks for writing up on my little tool, nice exposure :+1: 

I tried to do the merging, but I didn't succeed. Can I ask you to do the following:
- Make sure that your changes are based on my branch `pr/3`; I think you should be able to do that by merging in the latest from `pr/3` into your working branch `swift-2.1`
- Verify that the Travis build is working
- Create a new pull request and close this one.

Thanks again!

**Comment by svdo** [comment]
Didn't mean to close, bit too early. You can close if the above succeeds.

**Comment by trufae** [comment]
Can you review the patches to see why it is failing there?

**Comment by svdo** [comment]
Closing, not applicable anymore.

**Pull request closed without merging**
