### PR TITLE
Swift 2.1 on pr/3

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by trufae** [comment]
wtf i'll rebase instead of merge

**Comment by trufae** [comment]
Uhm. it fails to merge because you have merged my previous commit and pushed some stuff after it, that's why the pullreq looks like this... i have adapted the changes .. but there are some failing tests acording to travis. maybe because its running on a different OSX?

**Comment by trufae** [comment]
it's ok to merge this PR or do you want me to cleanup even more?

**Comment by svdo** [comment]
Are the tests working on your machine? I'm getting an `EXC_BAD_INSTRUCTION` on `ITCMSDecoder.swift` line 31...

**Comment by trufae** [comment]
yep it was running fine.. at least yesterday :P

**Comment by svdo** [comment]
Closing, not applicable anymore.

**Pull request closed without merging**
